### ISSUE TITLE
Update Khalti Payment Gateway

### ISSUE THREAD

**Issue by suman-bhatta** [bishal-rumba007/catering-user-app#6]
Please update the Khalti Payment Gateway integration to the latest version. The current integration needs to support the new API changes and improved security features.

Tasks:

1.     Update the Khalti Payment Gateway SDK to the latest version.

2.     Refactor the payment processing code to utilize the new API endpoints.

3.     Ensure all existing payment functionality is retained and works correctly.

 4.   Update any relevant documentation and configuration files.

Additional Information:

-     Link to the new Khalti API documentation: Khalti API Docs

-     Any additional notes or specific requirements related to the update.

**Comment by bishal-rumba007** [comment]
Duplicate of #5
